# Generated by Django 3.1.7 on 2021-04-01 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('papers', '0002_auto_20210331_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', djrichtextfield.models.RichTextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('isAnonymous', models.BooleanField(default=False)),
                ('votes', models.IntegerField(default=0)),
                ('paper_section', models.CharField(choices=[('whole', 'Whole Paper'), ('intro', 'Introduction'), ('method', 'Methodology'), ('results', 'Results'), ('discussion', 'Discussion'), ('conclusion', 'Conclusion')], default='whole', max_length=120)),
                ('comment_type', models.CharField(choices=[('question', 'Question'), ('review', 'Review'), ('summary', 'Summary')], default='review', max_length=120)),
                ('user_expertise', models.CharField(choices=[('novice', 'Novice'), ('familiar', 'Familiar'), ('expert', 'Expert'), ('leader', 'Leader')], default='familiar', max_length=120)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='papers.paper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', djrichtextfield.models.RichTextField()),
                ('votes', models.IntegerField(default=0)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
