# Generated by Django 3.1.7 on 2021-04-03 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20210402_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='created_date',
        ),
        migrations.AddField(
            model_name='reply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='isAnonymous',
            field=models.BooleanField(default=False),
        ),
    ]
