# Generated by Django 3.1.7 on 2021-03-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210312_0331'),
        ('core', '0003_auto_20210312_1537'),
    ]

    operations = [
    ]
