# Generated by Django 3.1.7 on 2021-03-23 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_merge_20210323_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Paper',
        ),
    ]
