# Generated by Django 3.1.7 on 2021-04-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOI', models.CharField(default='', max_length=200)),
                ('title', models.TextField(blank=True)),
                ('authors', models.TextField(blank=True)),
                ('year_published', models.CharField(blank=True, default='', max_length=200)),
                ('journal', models.CharField(blank=True, max_length=500)),
                ('abstract', models.TextField(blank=True)),
            ],
        ),
    ]
