# Generated by Django 3.1.7 on 2021-04-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='arxiv_id',
        ),
        migrations.AddField(
            model_name='paper',
            name='DOI',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='journal',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
