# Generated by Django 3.1.7 on 2021-04-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0002_auto_20210331_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='date_published',
        ),
        migrations.AddField(
            model_name='paper',
            name='year_published',
            field=models.CharField(default='', max_length=200),
        ),
    ]
