# Generated by Django 3.1.7 on 2021-04-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_auto_20210402_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='year_published',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
