# Generated by Django 3.1.7 on 2021-04-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_auto_20210402_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
